### ISSUE TITLE
Doesnt trigger <noscript>

### ISSUE THREAD

**Issue by MatsSvensson** [meetDeveloper/JavaScript-Switcher#3]
Its important to tell users who visit a site that needs JS to work, that some things like for example an order form doesn't work properly without  JS.

You do this by detecting if JS is activated, and display for example warning if its not.
I make sure to always do this.
The  standardized way to detecting  this, is by using the <nosript>-tag.

However, when you disable JS with THIS adddon, the  content in  noscript-tag is NOT displayed.
So its being done wrong somehow.

This can lead some some very difficult to diagnose errors, where for example users claim they have submitted something, because that clicked submit, and the page just reloaded.

As a developer, I have to give this addon a fail-review because of this.

**Comment by meetDeveloper** [comment]
@MatsSvensson I know about this problem, and there is some bug in mozilla that causes this thing to fail, I will look into it again and will improve the extension so that it is fixed, thanks for using it.

**Comment by meetDeveloper** [comment]
@MatsSvensson I have fixed the problem, I was not getting enough time, just got job, so was not able to focus, I have fixed the issue, can you confirm? and thanks for giving detailed problem statement, Firefox does not check CSP header (extension uses CSP headers for switching off JavaScript) for triggering noscript tags, I used a workaround and triggered them, when JavaScript is disable.
