### ISSUE TITLE
Breaks Firefox since 1.4.0

### ISSUE THREAD

**Issue by Grid405** [meetDeveloper/JavaScript-Switcher#4]
Unable to load any kind of website in Firefox 67.0.4 (64-Bit) since update to 1.4.0. Tested with all extensions disabled except JS Switcher.

**Comment by meetDeveloper** [comment]
@Grid405 Does this still occur?

**Comment by Grid405** [comment]
@meetDeveloper Yes, problem still exists.

**Comment by meetDeveloper** [comment]
@Grid405 Have you updated your browser? Can you do ctrl (cmd on mac) + shift + i and send me logs?

**Comment by Grid405** [comment]
@meetDeveloper Browser is up to date, currently running Firefox 69.0.1 (64-Bit) on Win 10. Console is empty, there are no logs. Firefox tries to connect to the requested host, but the screen stays blank and all it says in the bottom left corner is "Waiting for [host]". As soon as i deactivate the plugin, the connection is immidiately established. In the dev tools, under the network tab, there are no headers for the request, status field is also blank.

**Comment by meetDeveloper** [comment]
@Grid405 Can I get access to your system?

**Comment by meetDeveloper** [comment]
I meant I need logs

**Comment by meetDeveloper** [comment]
Unable to reproduce.
